language: node_js
node_js: stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- npm install -g gulp
- bower install
- gulp
script:
- ./travis-runner.sh
env:
  global:
    secure: PKBHGpIXqnquL1anrQ1k620gVYU4QSBlX9YMcL3lKvLN4Si+A1onyKdskAVwoEPyCM3oU0ksS8HpwRbZVn6WStQAtXiQwm2xq3XhQxeEs0n5r30spU90L1oZUCGfC9o3p4/8q77KzIBi3ga3G5pBf4XA9MndFQgCrmID0HC9W+CAy8/T1c+pnZezOP0wWvmdV382y+KCPcOSNetEd+dCMTOU0n4L7TSnJFqDZBGHL9eVUTgJWVcjT0EMKsSit0j7uVrAp0IOJESUp5KSDvCT5uMsA9x6HFFt68hFQ0PwatjfRxv7wE9ak/pgDNk2IIzMo20s5ROCFzON0TwWql7AjDTUTOwYTz5B03aalL6E1rnN5wMLYJ1c+R/nifzyo6e42E5zgYVnrbbcH4G3EAdpp+cWAknyT+rV5uDqLsdW8e0fMm/5uRh8WLofLyP9uPatsTU11S8tKSEz61f6FFE64+ROX5y+r+/E5dJvigSrf3sEEwrdTTTATT7kBl2wK8deNZh3+4J/6+ZV/r/Qu5BcYWV7YSxiirQLxfzC6fjT2P/kwVXUJdei+S5ao9/+wheeZWExVII3R5C0EOq4Er9tFGQkA4jgoLHEXSI9600RAweRqFG1pYQqZBS7qWvZiYkyH75L1hRcBg/++OrXXr/gxQaZQX3s5eNCHbC/GcNonoc=
