language: node_js
node_js: stable
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- npm install -g gulp
- bower install
- gulp
script:
- ./travis-runner.sh
env:
  global:
    secure: tjcW9+oBVrmUgVpdTggZh/pLb2xCUzmnLXCdFEipK5a/lz3jefC4nxeAYCZyMWcMuTUL5I3Yr61G84gcFQPRh7GqVcKVYMvHG+e5BKtRfjN4Ln5uOvBvT1g6jeLgbsnyN7Ony6AGS6VQMWduEHM7LDchr2P7qQnCKMtsdIL5ADlbFvQJdl24IhePoq+Etf7SAMjiKdvv0/rzT8W/sEr3iK3ZmmML6d5yqKjyTwDBndT5WvUd3e2otxQEjQHIhX0H4Q6kPrX0lj5BoAqHoQNV+kkhAJcQs4KOK7o1Vbi5AYQitmzzFf9XlM89OSqsFcN4Zdlvn8j/jmZ44DRi/fKGoo2DBSrGEgVAV4nf16JoY/pXbMfYJbw9JVlCEioWqq/PQkKMxJNT3t7G0w1KmQkqLKouJvZjS91ioVFNr53dLg1wQmQHVrwwNbr37fo8GITS4MdeasS56kuXVMjhT0vRSLfli1kIToRDMKyJqebXb5oUOyDZ1MF5HCK+sb+PEYOdERGwl0ejW7Om45wzVElPliKedaYMai54x9rdH9uGPeRyaaskSbuiQcOH7MrO3Q5MYejGDunIBSiesXCYjIKJV+OXH8C1rzrYrou7xL0Z1fiam2gDafFNKKk6H3vnpRYnjtCX5EKd2PqFV0fvQuLVcdzlt7vk/E1c00tsoxI3Y0A=
